### ISSUE TITLE
Create a Landing page

### ISSUE THREAD

**Issue by shrey1608** [mann27/Albums#50]

**Comment by shrey1608** [comment]
https://mdbootstrap.com/previews/free-templates/portfolio/full-page-gallery.html The landing page theme will be this. necessary edits will be done. please approve or suggest @mann27 @ExpressHermes

**Comment by ExpressHermes** [comment]
This looks good. A few considerations:

- Replace the main carousel with a single image

- This template is made from material bootstrap instead of simple bootstrap. Which will make the our website a little heavy as we will be using both bootstrap as well as material bootstrap. Maybe try to find a bootstrap template.. Or if you can code the landing in bootstrap.

**Comment by shrey1608** [comment]
ok i will take the considerations and create according to it

**Comment by shrey1608** [comment]
![image](https://user-images.githubusercontent.com/45357209/97774816-27f48700-1b81-11eb-8951-9e10edfab86a.png)
![image](https://user-images.githubusercontent.com/45357209/97774841-45295580-1b81-11eb-8b72-28dfacf5e41f.png)
Is this fine there will be a image in the header and also in the cards? @ExpressHermes @mann27

**Comment by ExpressHermes** [comment]
Looks good! Make sure to edit it accordingly such that unnecessary details are not included while required information is there for each album/song

**Comment by shrey1608** [comment]
ya ya i will do that

**Comment by shrey1608** [comment]
Solved in #52 .
